// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// covSEard
arma::mat covSEard(const arma::mat& X, const arma::mat& Z, const arma::vec& h);
RcppExport SEXP _gpmss_covSEard(SEXP XSEXP, SEXP ZSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(covSEard(X, Z, h));
    return rcpp_result_gen;
END_RCPP
}
// covSEiso
arma::mat covSEiso(const arma::mat& X, const arma::mat& Z, const arma::vec& h);
RcppExport SEXP _gpmss_covSEiso(SEXP XSEXP, SEXP ZSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(covSEiso(X, Z, h));
    return rcpp_result_gen;
END_RCPP
}
// cholsove
arma::mat cholsove(const arma::mat& L, const arma::mat& B);
RcppExport SEXP _gpmss_cholsove(SEXP LSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cholsove(L, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gpmss_covSEard", (DL_FUNC) &_gpmss_covSEard, 3},
    {"_gpmss_covSEiso", (DL_FUNC) &_gpmss_covSEiso, 3},
    {"_gpmss_cholsove", (DL_FUNC) &_gpmss_cholsove, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpmss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
