# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.covSEard <- function(X, Z, h) {
    .Call(`_gpmss_covSEard`, X, Z, h)
}

.covSEiso <- function(X, Z, h) {
    .Call(`_gpmss_covSEiso`, X, Z, h)
}

cholsove <- function(L, B) {
    .Call(`_gpmss_cholsove`, L, B)
}

